version: '3'

services:

    app1:
        build: ./web
        environment:
            - APACHE_RUN_USER=#1000
            - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d/:/usr/local/etc/php/custom.d/
        volumes:
            - ${APP_PATH_HOST1}:${APP_PATH_CONTAINER}
            - ./web/php-ini/:/usr/local/etc/php/custom.d/
        ports:
            - 8081:80
        working_dir: ${APP_PATH_CONTAINER}

# master
    redis:
        image: redis
        ports:
            - 6479:6379
        volumes:
            - ${REDIS_M_HOST}:${REDIS_M_CONTAINER}
            - ${REDIS_CONF_HOST}:${REDIS_CONF_CONTAINER}
        command: redis-server ${REDIS_CONF_CONTAINER}/master.conf

    slave:
        build: ./slave
        command: redis-server /etc/redis/slave.conf

    sentinel:
        build: ./sentinel
        command: redis-server /etc/redis/sentinel.conf --sentinel

networks:
  default:
    external:
      name: docker_network

